### ISSUE TITLE
Documentation - Loading nested documents

### ISSUE THREAD

**Issue by 110100110101** [ravendb/ravendb-nodejs-client#110]
Not exactly an issue, but I can't find any example or implementation on the internet how to load nested documents in Javascript or Typescript; Though on C# and Java it is documented. Submitted examples will be greatly appreciated. Thanks!

**Comment by ayende** [comment]
Can you explain what you mean by nested documents?

**Comment by 110100110101** [comment]
I apologize for not explaining it well. What I mean on my question above was about this stuff [How to handle document relationships](https://ravendb.net/docs/article-page/4.0/Csharp/client-api/how-to/handle-document-relationships#client-api--how-to-handle-document-relationships). How it is implemented on Javascript? If so, may you please give us an example? Thanks!

**Comment by gregolsky** [comment]
It's handled similarly to how Java does it. I added example on using `include()`:
https://github.com/ravendb/ravendb-nodejs-client#loading-documents-with-includes

**Comment by 110100110101** [comment]
Thank you guys for adding an example.
