### ISSUE TITLE
Document is stored but always added to the `@empty` collection

### ISSUE THREAD

**Issue by hanssens** [ravendb/ravendb-nodejs-client#204]
**Summary:**  
Using the v4.1.5 Node.js client, and RavenDB server 4.1.5-patch-41012 (Docker), storing a document is stored but always added to the `@empty` collection, instead of the actual collection. See the two examples below.

I've looked at the [Storing Entities section of the docs](https://ravendb.net/docs/article-page/4.1/nodejs/client-api/session/storing-entities). Note this behaviour occurs both when **using a class**, like `Foo` in the example below, or when using an object literal and specifying the collection name. 

This behaviour occurs both on a new, non-existing collection as well as when the collection already exists.

Lastly, I've tried several overloads of the `session.store()` function; with/without ID, different ID strategies, providing a collection name etc. Just can't seem to find the correct way. 

---

**Expected behaviour:**  
- New collection is created, if not exists, and document is added to it
- Or, document is added to existing collection

**Actual behaviour:**  
- Document is added to @empty collection

**Example:**  

```typescript
	export class Foo {
	    public foo: number | undefined;
	    public bar: string | undefined;
	}

    test('example 1 - store should save new collection, for class', async () => {
        const raw = `{
            "foo": 42,
            "bar": "lorem ipsum"
        }`;

        const store = new DocumentStore(settings.endpoint, settings.database);
        store.initialize();
        const session = await store.openSession();
        const document: Foo = JSON.parse(raw);

        // Note: Tried several options here:
        // await session.store(document);
        // await session.store(document, 'foo/');
        // await session.store(document, 'foo/', { documentType: Foo });
        await session.store(document, 'foo/', 'Foo');
        await session.saveChanges();

        /* Result:
            {
                "foo": 42,
                "bar": "lorem ipsum",
                "@metadata": {
                    "@nested-object-types": {},
                    "Raven-Node-Type": null
                }
            }
        */
    });

    test('example 2 - store should save new collection, for object literal', async () => {
        const raw = `{
            "foo": 42,
            "bar": "lorem ipsum"
        }`;

        const store = new DocumentStore(settings.endpoint, settings.database);
        store.conventions.findCollectionNameForObjectLiteral = (entity: any) => entity['collection'];
        store.initialize();
        const session = await store.openSession();
        const document = JSON.parse(raw);

        // Note: Also tried several options, mentioned in 'example 1'
        await session.store(document, 'foo/');
        await session.saveChanges();
    });


```

**Comment by ayende** [comment]
@gregolsky @Danielle9897 Can you take a look?

**Comment by Danielle9897** [comment]
When using a class for the entity to be saved - Pass the document as an **object instance of the class** to session.store().  

Can follow the example in:
https://github.com/ravendb/ravendb-nodejs-client#usage-with-typescript

```
let product = new Product(
    null, 'iPhone X', 999.99, 'USD', 64, 'Apple', true, new Date('2017-10-01T00:00:00')
  );

  await session.store<Product>(product);
```

1. To work with object literals for entities - See https://github.com/ravendb/ravendb-nodejs-client#using-object-literals-for-entities
2. To work with classes for entities - See https://github.com/ravendb/ravendb-nodejs-client#using-classes-for-entities
