### ISSUE TITLE
Support for Counters

### ISSUE THREAD

**Issue by xe6** [ravendb/ravendb-nodejs-client#209]
Hello! I was wondering if you consider implementing [counters API](https://ravendb.net/docs/article-page/4.2/Csharp/client-api/session/counters/overview#overview) in node client?
Maybe I am missing something from the official docs, but I have failed to locate the ability to interact with counters. 

Thank you in advance!

**Comment by gregolsky** [comment]
@Assstarte, the support for the counters API is complete in the node.js client. Unfortunately the documentation lacks node.js usage examples. We will improve it and include the missing pieces. I'm sorry for the inconvenience.

Before that happens you can consider looking at the unit tests to get a feeling of the API. Please see here:
https://github.com/ravendb/ravendb-nodejs-client/tree/v4.1/test/Ported/Counters

If you have any more questions please let us know.

**Comment by xe6** [comment]
@gregolsky Thanks for good point! I reviewed the code in tests and I think that pretty much covers my concern. You could still leave this issue as open till you implpement documentation. It is up to you though.

Huge thanks and I should say I really enjoy your project and idea behind it. :)

**Comment by gregolsky** [comment]
I created an issue on our YouTrack, so I'll just close this one.
