### ISSUE TITLE
Next version release?

### ISSUE THREAD

**Issue by MilesWells** [ravendb/ravendb-nodejs-client#214]
Hello!

The company I work for is attempting to utilize this client in TypeScript. We ran into the issue that #212 fixes, but we noticed the build hadn't triggered a publish to npm. Just wondering if there's a release schedule for this package and when the next version will be published.

Thanks!

**Comment by gregolsky** [comment]
Hello @MilesWells ,
Just wanted to let you know `4.1.7` just landed on npm.
