### ISSUE TITLE
Using load with includes returns null for documents that were previously stored

### ISSUE THREAD

**Issue by nemanja-tosic** [ravendb/ravendb-nodejs-client#256]
If we store and load within the same session without invoking saveChanges and with includes, like so:

```
await session.store({ id: '1', path: [] });
const doc = await session.load('1', {
  includes: ['path']
});

// expect document, actual null
console.log(doc);
```

the doc is null. Same example without includes or with invoking saveChanges works fine.

Reproducible in tests, namely ReadmeSamples => "loading data with include()".

**Comment by nemanja-tosic** [comment]
Opened an issue on YouTrack as well, I suppose that's the prefered place.

**Comment by ayende** [comment]
Yes, we'll continue handling it there.
