### ISSUE TITLE
Cannot find type definition file for 'stream-json'

### ISSUE THREAD

**Issue by st0014** [ravendb/ravendb-nodejs-client#261]
When including this in my Typescript project, I get the following error when building it:

node_modules/ravendb/dist/Mapping/Json/Streams/TransformKeysJsonStream.d.ts:1:23 - error TS2688: Cannot find type definition file for 'stream-json'.

1 /// <reference types="stream-json" />

**Comment by ml054** [comment]
Hi @st0014, 

Issue is reported in our bug tracker:  https://issues.hibernatingrhinos.com/issue/RDBC-429
 

As temporary workaround please install typings for stream-json manually 
```
npm install @types/stream-json
```

**Comment by ml054** [comment]
Fixed in https://github.com/ravendb/ravendb-nodejs-client/releases/tag/5.0.1
