### ISSUE TITLE
Issue with 5.0.1

### ISSUE THREAD

**Issue by st0014** [ravendb/ravendb-nodejs-client#268]
Switched to 5.0.1, and when building, the following errors occured:

node_modules/ravendb/dist/Types/index.d.ts:49:28 - error TS1005: ']' expected.

49     [K in keyof T & string as `${Capitalize<K>}`]: T[K] extends Array<infer R> ? R extends string ? R[] : ServerCasing<R>[] : T[K] extends object ? ServerCasing<T[K]> : T[K];
                              ~~

node_modules/ravendb/dist/Types/index.d.ts:49:47 - error TS1005: '(' expected.

49     [K in keyof T & string as `${Capitalize<K>}`]: T[K] extends Array<infer R> ? R extends string ? R[] : ServerCasing<R>[] : T[K] extends object ? ServerCasing<T[K]> : T[K];
                                                 ~

node_modules/ravendb/dist/Types/index.d.ts:51:1 - error TS1160: Unterminated template literal.

51

**Comment by ml054** [comment]
What's your TypeScript version?

**Comment by ml054** [comment]
@st0014 Confirmed this is a bug. In package.json we require typescript 4.0+. But Capitalize etc are available in TS 4.1+. Will fix that soon.

**Comment by ml054** [comment]
fixed in https://github.com/ravendb/ravendb-nodejs-client/releases/tag/5.0.2
