### ISSUE TITLE
Can I use the as clause?

### ISSUE THREAD

**Issue by secmin** [ravendb/ravendb-nodejs-client#285]
RQL can use as clause, but can I use it in js sdk?
Example
const data = await session.query({ collection: 'Users'}).as('id', 'user_id')

// { user_id: 50465465 }

This is what it looks like.
I want to achieve this without using indexes or RQL.

**Comment by ml054** [comment]
Please have a look at following test:
https://github.com/ravendb/ravendb-nodejs-client/blob/v5.0/test/Ported/Issues/RavenDB_14811.ts

Here you have an example of projecting fields (w/o rename):
https://github.com/ravendb/ravendb-nodejs-client/blob/v5.0/test/Ported/Issues/RavenDB_14811.ts#L32

With rename:
https://github.com/ravendb/ravendb-nodejs-client/blob/v5.0/test/Ported/Issues/RavenDB_14811.ts#L46

**Comment by secmin** [comment]
@ml054 
Thank you very much. Thank you for your help.
