### ISSUE TITLE
TimeSeriesRangeAggregation.asTypedEntry not producing expected results

### ISSUE THREAD

**Issue by kamranayub** [ravendb/ravendb-nodejs-client#287]
Given the following RQL I am using to retrieve trading time series data:

```ts
const aggregatedHistoryQueryResult = await session
    .query(MarketSymbol)
    .whereEquals("id", symbolId)
    .selectTimeSeries(
      (builder) =>
        builder.raw(
          `from history 
          between $start and $end 
          group by $groupBy
          select first(), last(), min(), max()`
        ),
      TimeSeriesAggregationResult
    )
    .addParameter("start", fromDate)
    .addParameter("end", dayjs.utc().toDate())
    .addParameter("groupBy", groupingAction)
    .firstOrNull();
```

And this is what RavenDB is returning as the aggregation entry:

```js
TimeSeriesRangeAggregation {
  key: null,
  count: [ 1416, 1416, 1416, 1416 ],
  first: [ 39147.8, 39141.6, 39185.5, 39107.4 ],
  last: [ 38404.5, 38415, 38428.2, 38388.9 ],
  min: [ 37780.2, 37781.5, 37860.7, 37653.6 ],
  max: [ 39751.9, 39751.9, 39774, 39678.2 ],
  from: 2021-08-02T03:00:00.000Z,
  to: 2021-08-03T03:00:00.000Z
}
```

When I call `asTypedEntry` and pass the following class:

```ts
class SymbolPrice {
  open: number;
  close: number;
  high: number;
  low: number;

  static TIME_SERIES_VALUES: TimeSeriesValue<SymbolPrice> = [
    { field: "open", name: "Open" },
    { field: "close", name: "Close" },
    { field: "high", name: "High" },
    { field: "low", name: "Low" },
  ];
}

aggregatedHistoryQueryResult.results[0].asTypedEntry(SymbolPrice);
```

It is producing `SymbolPrice` instances that only have an `open` value set, and `undefined` set for the rest of the values:

```js
TypedTimeSeriesRangeAggregation {
  from: 2021-08-02T03:00:00.000Z,
  to: 2021-08-03T03:00:00.000Z,
  min: SymbolPrice {
    open: 37780.2,
    close: undefined,
    high: undefined,
    low: undefined
  },
  max: SymbolPrice {
    open: 39751.9,
    close: undefined,
    high: undefined,
    low: undefined
  },
  first: SymbolPrice {
    open: 39147.8,
    close: undefined,
    high: undefined,
    low: undefined
  },
  last: SymbolPrice {
    open: 38404.5,
    close: undefined,
    high: undefined,
    low: undefined
  },
  sum: null,
  count: SymbolPrice {
    open: 1416,
    close: undefined,
    high: undefined,
    low: undefined
  },
  average: null
}
```

What I expect is that all the values are filled in.

I believe it has to do with this logic with `asRollup` (I am not exactly sure what it's purpose is):

https://github.com/ravendb/ravendb-nodejs-client/blob/30a0b6212d9f0b230d3ad7072864a5791db555a8/src/Documents/Session/TimeSeries/TimeSeriesValuesHelper.ts#L83-L85

If it was passed as `false`, I think it would work like I expect (and how the C# code works, since I ported this logic from .NET).

I can workaround this by not using `asTypedEntry` for now.

**Comment by ayende** [comment]
I think that the issue is here:

https://github.com/ravendb/ravendb-nodejs-client/blob/30a0b6212d9f0b230d3ad7072864a5791db555a8/src/Documents/Queries/TimeSeries/TimeSeriesRangeAggregation.ts#L21-L27

We are passing true here, where we are doing these skips.

@ml054 Can you take a look, this looks wrong to me.

**Comment by ml054** [comment]
@kamranayub I've manged to reproduce this issue. It is reported here: https://issues.hibernatingrhinos.com/issue/RDBC-501

we should pass false here instead of true.

Working on fix.

**Comment by kamranayub** [comment]
Thank you team! 💯
