### ISSUE TITLE
load methods could reasonably return null and interface should reflect that

### ISSUE THREAD

**Issue by ngbrown** [ravendb/ravendb-nodejs-client#298]
An example `load` method:

https://github.com/ravendb/ravendb-nodejs-client/blob/778c70f48c96b55272a9668764139f6038208515/src/Documents/Session/IDocumentSession.ts#L150

The return is currently precluded from being null, and when putting a custom type in, you can't do `load<MyDocument | null>` because that doesn't extend `object`.

All methods that could return `null` or `undefined` should be updated to signify that.

**Comment by ayende** [comment]
Something to consider is the backward compatability issue.

**Comment by ngbrown** [comment]
If these were externally contributed types such in DefinitelyTyped , I think the change would be accepted as a minor update because it is a more accurate representation of the behavior of the library... ([ref](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57473#issuecomment-1010229613))

The behavior at runtime wouldn't change. And it also appears that the version of the client is synchronized to the server...

It could break some typescript compiler checked builds (not babel, esbuild, etc.) on the next package update or that aren't using a `package-lock.json` file; if the returned value isn't already being checked for the `null` condition.

**Comment by ayende** [comment]
@ml054 thoughts?

**Comment by ml054** [comment]
Hi, @ngbrown Typings are distributed along with package. However we don't use strict null checking feature. Typescript version we use is 4.0 to avoid using features which are not backward compatible. 

Anyway I like an idea of introducing strong type checking to have even better insight about types.

**Comment by ml054** [comment]
@ngbrown Please have a look at comment: https://issues.hibernatingrhinos.com/issue/RDBC-550#focus=Comments-67-281341.0-0

Closing this issue here.

**Comment by ngbrown** [comment]
Hi @ml054 Thanks for updating me. I added a comment to your reference issue. I don't know that strict null checks need to be enabled for the result types to be more correct. If some code base isn't handling the possibility of a load by id returning `null` from the database, do they have a logic problem they should be warned about?

**Comment by ml054** [comment]
@ngbrown This should be partially fixed in 5.2.1. We don't have full strictNullChecks, but most of session related methods has `| null`, so UX should be way way better. 

Thanks for suggestion.
