### ISSUE TITLE
Incorrect ModifiedDocument returned in afterSaveChanges session event

### ISSUE THREAD

**Issue by jhahn** [ravendb/ravendb-nodejs-client#352]
## Exposition

We’re running the NodeJS client against documents with keys that aren't camel-cased. In some cases, the keys (e.g. SIPCall) cannot be (easily) round-trip converted between camel and pascal case without losing the original key name. So we’re using the original key names, and have opted _not_ to use `entityFieldNameConvention` or `remoteEntityFieldNameConvention`.

As part of our application, we load documents containing keys that are _not_ camel-cased into a session. When we patch those documents (with a deferred session command) and save the session changes, the resulting modified document (as accessed through an `afterSaveChanges` event) contains an object with both the original (non camel-cased) keys (with the old values), and camel-cased keys with the new (modified) values.

This is an example of the kind of entity that's returned:

```
{
  Name: "old name",
  SIPCall: "old value",
  name: "new name",
  sipCall: "new value"
}
```

## How it happens…

`SingleNodeBatchCommand` requests that its result keys be transformed…
https://github.com/ravendb/ravendb-nodejs-client/blob/70834f630ee18e43e36e027da6549666b203457b/src/Documents/Commands/Batches/SingleNodeBatchCommand.ts#L141-L148

…which sets `streamKeyCaseTransform` in the `RavenCommandResponsePipeline`…
https://github.com/ravendb/ravendb-nodejs-client/blob/333bc5477dd3435e621fac4467ee4d72bf42521f/src/Http/RavenCommandResponsePipeline.ts#L101-L122

…which adds `ObjectKeyCaseTransformStream` to the stream when processing the results…
https://github.com/ravendb/ravendb-nodejs-client/blob/333bc5477dd3435e621fac4467ee4d72bf42521f/src/Http/RavenCommandResponsePipeline.ts#L202-L206

…which, by default, is recursive, descending into `ModifiedDocument` and irreversibly altering the returned document object keys.
https://github.com/ravendb/ravendb-nodejs-client/blob/4fb534c32da49c3fd4602173c43fde44837b7155/src/Mapping/Json/Streams/ObjectKeyCaseTransformStream.ts#L21-L24

## Failing test case

```typescript
it("returns correct modified document after patch", async () => {
        class PascalDoc {
            public SIPCall: string
        }
        {
            const session = store.openSession();
            const pascalDoc = new PascalDoc();
            pascalDoc.SIPCall = "RavenDB";

            await session.store(pascalDoc, "pascal/1");
            await session.saveChanges();
        }
        let modifiedDocument
        store.addSessionListener("afterSaveChanges", event => {
            modifiedDocument = event.entity
        });

        const session = store.openSession()
        await session.load("pascal/1")
        const patchRequest = PatchRequest.forScript("this.SIPCall = \"Patched\"");
        session.advanced.defer(new PatchCommandData("pascal/1", null, patchRequest))
        await session.saveChanges();

        assert.strictEqual(modifiedDocument.SIPCall, "Patched")
        assert.ok(!("sipCall" in modifiedDocument))
});
```

## Potential fix

We worked around the issue by adding `ignorePaths` to the options passed to `objectKeysTransform`. 

```typescript
this.result = await RavenCommandResponsePipeline.create<BatchCommandResult>()
    .collectBody(_ => body = _)
    .parseJsonSync() // TODO: consider parseJsonAsync()
    .objectKeysTransform({
        defaultTransform: "camel",
        ignoreKeys: [/^@/],
        ignorePaths: [/results\.\[\]\.modifiedDocument\./i],
    })
    .process(bodyStream);
```

Original:
https://github.com/ravendb/ravendb-nodejs-client/blob/70834f630ee18e43e36e027da6549666b203457b/src/Documents/Commands/Batches/SingleNodeBatchCommand.ts#L141-L148

This works for us, but we’re not sure if this fix is broadly applicable, as maintaining compatibility with the existing case-conversion conventions wasn’t a priority for us.

**Comment by ayende** [comment]
Hi,
The actual problem is that you are running using `"this.SIPCall = \"Patched\""`, which is sending the _raw_ string for execution on the server side. Which will create the `SIPCall` property there.

For compatability with the rest of the naming convention, you need to use the property name on the server.

Your change is making a pretty big change in the internals result that are coming from the server.
It *isn't* modifying the change on the server side, mind. Just modifying it in place as the result.

**Comment by jhahn** [comment]
Thanks for the response. _(and great work on RavenDB!)_

Sorry I wasn’t more clear in the initial report. The shape of the documents on the server _do_ match the raw string we send for execution. An example document might look like:

```
{
  RouteName: "Direct",
  SIPCall: “8712095”
}
```

Our issue is that the _NodeJS client_ is transforming the results from the server, and there’s seemingly no way to disable or configure that transformation.

**Comment by ayende** [comment]
Oh, I see. We'll have one of the node.js client people look into that in more depth

**Comment by ml054** [comment]
https://issues.hibernatingrhinos.com/issue/RDBC-682/Incorrect-ModifiedDocument-returned-in-afterSaveChanges-session-event

**Comment by ml054** [comment]
https://github.com/ravendb/ravendb-nodejs-client/pull/358

**Comment by ml054** [comment]
@jhahn Fixed. Thanks for sharing this issue with us.
