### ISSUE TITLE
Remove @Metadata when querying

### ISSUE THREAD

**Issue by tzarger** [ravendb/ravendb-nodejs-client#382]
I am trying out NextJS 13 async queries directly in Server Components and it complains that `Warning: Only plain objects can be passed to Client Components from Server Components. Classes or other objects with methods are not supported.`

The actual issue is there are values in the `@metadata` that appear to not be serializable or at least when I manually `remove the @metadata` all works fine. I normally use GraphQL every since I have been working with RavenDB when back in version 1 and didn't even realize the metadata comes with a query as I also had to load the metadata manually when I wanted to say add a expires date.

I could not find a store convention or anything like that to strip the `@metadata` when loading stuff. Did I miss something?

Thanks!

**Comment by ppekrol** [comment]
Hi @tzarger 

There is no option to remove the `@metadata` from the query. The information there is used by the RavenDB Client API and is critical for the API to function properly.
