### ISSUE TITLE
Deleting does not work in bulk

### ISSUE THREAD

**Issue by Avi-E-Koenig** [ravendb/ravendb-nodejs-client#405]
Tried several variations of the docs
https://www.npmjs.com/package/ravendb#crud-example

Nothing works on deletion

```typescript
export async function deleteCollection(collectionName: string): Promise<void> {
    const session = store.openSession();
    try {
        const documents = (await session
            .query({ collection: collectionName })
            .all()) as RavenDocument[];
            // data is fetched properly here
        for (const document of documents) {
            await session.delete(document);
        }
        await session.saveChanges();
    } catch (error) {
        console.error('Error deleting documents:', error);
        throw error;
    } finally {
        session.dispose();
    }
}
```

**Comment by ml054** [comment]
Can you share an exception with us? 

For deleting entire collection I'd go with DeleteByQueryOperation. 

Code examples:
https://github.com/ravendb/ravendb-nodejs-client/blob/bed9ee9ca9982c03d40eae35f5e2fdbe6388ed2a/test/Documents/Operations/DeleteByQueryTest.ts#L13

**Comment by Avi-E-Koenig** [comment]
Thank you for your reply.
I hope to review your DB again in the future.

**Comment by ml054** [comment]
I'm happy I could help. Can I assume we can close this ticket?

**Comment by Avi-E-Koenig** [comment]
Yes please do.
