### ISSUE TITLE
V6: Disposing the store isn't mentioned in the readme.

### ISSUE THREAD

**Issue by ngbrown** [ravendb/ravendb-nodejs-client#453]
I wrote a utility script in Node.js and I'm using an `async` main()/top-level script. After the RavenDB operations are complete, the `node` process won't exit.

I see that the tests put the `.dispose()` calls in a `finally`, but it's not mentioned in the `README.md` file. It should be mentioned that disposing the `session` and especially the `store` is required.

After I added at least `store.dispose()`, then the `node` process would exit normally.

I'm not sure if this was an issue with the V5 client, but it is in the V6 client.

**Comment by Danielle9897** [comment]
Created an issue to handle this:
https://issues.hibernatingrhinos.com/issue/RDBC-870/Add-explanation-of-store.dispose-to-the-readme

**Comment by ml054** [comment]
fixed. Thanks @ngbrown for suggestion.
