### ISSUE TITLE
Support for attachments

### ISSUE THREAD

**Issue by germanftorres** [ravendb/ravendb-nodejs-client#95]
Hi!

In 4.0.0-rc3 there was support for attachments via PutAttachmentOperation, although the `session.advanced` was lacking the same api as it's C# counterpart. In the RTM, PutAttachmentOperation has been removed but we don't have support yet in the `session.advanced` api. Any plans to bring the support for attachments back any time soon?

Great to have support for ravendb in nodejs!!

Thanks!

Germán

**Comment by gregolsky** [comment]
Hi @germanftorres,

We keep the code in-sync with Java counterpart. Node.js client's feature set matches with where JVM client was in February now. We'll continue to add features to Node.js client to reach the full feature set of C# and JVM clients including attachments, changes API etc.

You can track the progress in this issue http://issues.hibernatingrhinos.com/issue/RDBC-147

**Comment by gregolsky** [comment]
Fixed in `4.0.2`.
See https://github.com/ravendb/ravendb-nodejs-client#attachments
